env: "production" # dev, staging, production
app:
  name: "My App"
  nameForCLI: "my-app"

httpServer:
  port: 8082

log:
  level: "debug"
  stacktraceLevel: "error" # debug, info, warn, error, dpanic, panic, fatal
  fileEnabled: false
  filePath: "log/log.log"
  maxAge: 1 # days to keep log files
  maxBackups: 10 # umber of log files

postgres:
  host: "postgres"
  port: 5432
  database: "my_database"
  schema: "my_schema"
  username: "my_user"
  password: "my_password"
  maxConnections: 20
  maxIdleConnections: 10

sentry:
  dsn: ""
  environment: "production"
  release: "go-boilerplate@v0.1.0"
  debug: false

schedules:
  - cron: "0 */30 * * * *"
    job: "DoSomething"
