name: Analysis

on:
  workflow_run:
    workflows: ["Testing"]
    types:
      - completed

jobs:
  build:
    name: Build
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v2
        with:
          name: unit-test-coverage
          path: .
      - uses: actions/download-artifact@v2
        with:
          name: api-test-coverage
          path: .
      # Perform your desired analysis on the downloaded coverage files in the "artifacts" directory
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
